version: '3'

services: 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    restart: unless-stopped
    depends_on: 
      - postgres
    networks:
      - backend

  postgres:
    image: "postgres:alpine"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend: